default: &default
  adapter: postgresql
  encoding: unicode
  database: correios_seminario
  pool: 5
  username: postgres
  password: root
  host: localhost


development:
  adapter: postgresql
  encoding: unicode
  database: correios_seminario
  pool: 5
  username: postgres
  password: root
  host: localhost